# Importing packages

In [1]:
import keras
from keras import Sequential
from keras.layers.core import Dense, Dropout, Activation, Flatten
from keras.layers.convolutional import Convolution2D, MaxPooling2D
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

Using TensorFlow backend.


In [2]:
# reading the data
data = pd.read_csv("mnist_train.csv")

In [3]:
# viewing the data form
data.head()

label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...    28x19  28x20  \
0      5    0    0    0    0    0    0    0    0    0  ...        0      0   
1      0    0    0    0    0    0    0    0    0    0  ...        0      0   
2      4    0    0    0    0    0    0    0    0    0  ...        0      0   
3      1    0    0    0    0    0    0    0    0    0  ...        0      0   
4      9    0    0    0    0    0    0    0    0    0  ...        0      0   

   28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0      0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0      0  

[5 rows x 785 columns]

In [4]:
# reshaping the data into 28x28 array
data.iloc[3,1:].values.reshape(28,28).astype('uint8')

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0, 124, 253, 255,  63,   0,   0,   0,   0,
          0,   0],
       [  

In [5]:
# preprocessing the data

# storing Pixel array in form length width and channel in df_x
df_x = data.iloc[:,1:].values.reshape(len(data),28,28,1)

# storing the labels in y
y = data.iloc[:,0].values

In [6]:
# converting labels to categorial features

df_y = keras.utils.to_categorical(y,num_classes=10)

In [7]:
df_x = np.array(df_x)
df_y = np.array(df_y)

In [8]:
# labels
y

array([5, 0, 4, ..., 5, 6, 8], dtype=int64)

In [9]:
# categorial variables
df_y

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

In [10]:
df_x.shape

(60000, 28, 28, 1)

In [11]:
# train_test_split
x_train, x_test, y_train, y_test, = train_test_split(df_x,df_y,test_size=0.2, random_state=4)

In [12]:
# Setting up the CNN Model
model = Sequential()
model.add(Convolution2D(32,3,data_format='channels_last',activation='relu',input_shape=(28,28,1)))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Flatten())
model.add(Dense(100))
model.add(Dropout(0.5))
model.add(Dense(10))
model.add(Activation('softmax'))
model.compile(loss="categorical_crossentropy",optimizer='adadelta',metrics=['accuracy'])

In [13]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 26, 26, 32)        320       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 13, 13, 32)        0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 5408)              0         
_________________________________________________________________
dense_1 (Dense)              (None, 100)               540900    
_________________________________________________________________
dropout_1 (Dropout)          (None, 100)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 10)                1010      
_________________________________________________________________
activation_1 (Activation)    (None, 10)                0         
Total para

In [14]:
# fitting it with just 100 images first for testing
model.fit(x_train[1:100],y_train[1:100],validation_data=(x_test[1:20],y_test[1:20]),epochs=10)

Train on 99 samples, validate on 19 samples
Epoch 1/10
99/99 [==============================] - 5s 46ms/step - loss: 15.1712 - acc: 0.0505 - val_loss: 13.5731 - val_acc: 0.1579
Epoch 2/10
99/99 [==============================] - 0s 503us/step - loss: 15.4669 - acc: 0.0404 - val_loss: 13.5731 - val_acc: 0.1579
Epoch 3/10
99/99 [==============================] - 0s 504us/step - loss: 15.4669 - acc: 0.0404 - val_loss: 13.5731 - val_acc: 0.1579
Epoch 4/10
99/99 [==============================] - 0s 463us/step - loss: 15.4669 - acc: 0.0404 - val_loss: 13.5731 - val_acc: 0.1579
Epoch 5/10
99/99 [==============================] - 0s 494us/step - loss: 15.4669 - acc: 0.0404 - val_loss: 13.5731 - val_acc: 0.1579
Epoch 6/10
99/99 [==============================] - 0s 473us/step - loss: 15.4391 - acc: 0.0303 - val_loss: 13.5731 - val_acc: 0.1579
Epoch 7/10
99/99 [==============================] - 0s 494us/step - loss: 15.3040 - acc: 0.0505 - val_loss: 13.5731 - val_acc: 0.1579
Epoch 8/10
99/99 [=

In [15]:
# Training and validating the model
model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=10)

Train on 48000 samples, validate on 12000 samples
Epoch 1/10
48000/48000 [==============================] - 18s 374us/step - loss: 9.2699 - acc: 0.4214 - val_loss: 5.7810 - val_acc: 0.6386
Epoch 2/10
48000/48000 [==============================] - 19s 387us/step - loss: 3.5765 - acc: 0.7699 - val_loss: 1.2055 - val_acc: 0.9181
Epoch 3/10
48000/48000 [==============================] - 18s 368us/step - loss: 1.1850 - acc: 0.9185 - val_loss: 0.7119 - val_acc: 0.9499
Epoch 4/10
48000/48000 [==============================] - 17s 361us/step - loss: 0.8646 - acc: 0.9387 - val_loss: 0.5716 - val_acc: 0.9592
Epoch 5/10
48000/48000 [==============================] - 18s 366us/step - loss: 0.7297 - acc: 0.9483 - val_loss: 0.5452 - val_acc: 0.9614
Epoch 6/10
48000/48000 [==============================] - 17s 362us/step - loss: 0.6558 - acc: 0.9529 - val_loss: 0.4456 - val_acc: 0.9671
Epoch 7/10
48000/48000 [==============================] - 17s 365us/step - loss: 0.5767 - acc: 0.9579 - val_loss: 0.

In [16]:
model.evaluate(x_test,y_test)

12000/12000 [==============================] - 1s 117us/step


[0.3453048891849812, 0.972]

In [17]:
test_df = pd.read_csv('mnist_test.csv')

In [18]:
# reshaping the data into 28x28 array
test_df.iloc[3,1:].values.reshape(28,28).astype('uint8')

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  11,
        150, 253, 202,  31,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  37,
        251, 251, 253, 107,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  

In [19]:
# preprocessing the data

# storing Pixel array in form length width and channel in df_x
df_x = test_df.iloc[:,1:].values.reshape(len(test_df),28,28,1)

In [20]:
prediction = model.predict(df_x)

In [21]:
prediction[:5]

array([[0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 0.000000e+00, 1.000000e+00,
        0.000000e+00, 0.000000e+00],
       [0.000000e+00, 0.000000e+00, 1.000000e+00, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        0.000000e+00, 0.000000e+00],
       [0.000000e+00, 1.000000e+00, 0.000000e+00, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        0.000000e+00, 0.000000e+00],
       [1.000000e+00, 0.000000e+00, 2.732922e-37, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        0.000000e+00, 0.000000e+00],
       [0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        1.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        0.000000e+00, 0.000000e+00]], dtype=float32)

In [22]:
dataset = pd.DataFrame({'0':prediction[:,0], '1':prediction[:,1], '2':prediction[:,2], '3':prediction[:,3], '4':prediction[:,4], '5':prediction[:,5], '6':prediction[:,6], '7':prediction[:,7], '8':prediction[:,8], '9':prediction[:,9]})

In [23]:
dataset.head()

0    1             2    3    4    5    6    7    8    9
0  0.0  0.0  0.000000e+00  0.0  0.0  0.0  0.0  1.0  0.0  0.0
1  0.0  0.0  1.000000e+00  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2  0.0  1.0  0.000000e+00  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3  1.0  0.0  2.732922e-37  0.0  0.0  0.0  0.0  0.0  0.0  0.0
4  0.0  0.0  0.000000e+00  0.0  1.0  0.0  0.0  0.0  0.0  0.0

In [25]:
test_df.label.head()

0    7
1    2
2    1
3    0
4    4
Name: label, dtype: int64

# We can see that the actual and predicted digits are same in cell 23 and 25